### ISSUE TITLE
Unknown variable; There is no variable named "system_node_iam_role"., and 1 other diagnostic(s)

### ISSUE THREAD

**Issue by dmathew-pendosystems** [spender0/terraform-aws-eks#1]
Getting this error

* data.template_file.config_map_aws_auth: data.template_file.config_map_aws_auth: failed to render : <template_file>:8,18-38: Unknown variable; There is no variable named "system_node_iam_role"., and 1 other diagnostic(s)

**Comment by spender0** [comment]
@dmathew-pendosystems  thank you, fixed
